#Set of libraries used at some point in the model
install.packages("ggplot2")
install.packages("knitr")
install.packages("readxl")
install.packages("tidyr")
install.packages("cowplot")
install.packages("reshape2")
install.packages("ggrepel")
install.packages("ggthemes")
install.packages("scales")
